package job

import (
	"github.com/PeopleAdmin/pdfcombiner/fixtures"
	"github.com/stretchr/testify/assert"
	"testing"
)

var decodedExpectation = fixtures.BlankDoc

// The Base64 representation of the above file as generated by the following:
//
//   Base64.encode64(Zlib::deflate(File.read(pdf)))
//
var encoded = `
eJx9UU1PwkAQve+vmEuPsh/tFkkIB1ASokYEb4TDSqdYA13dLgn653W2rdgE
4h462dn35r03jeY30yvZi1n0TYdJEGBf3thwCHzi0HjrYJhjnguhhRB9JUQq
qfap4ojxubPZYYP/gkYjhmUWpqrO9OfPdyQN483ObmmQ2WIFMQEWHUJ8Rqhx
jE/sofQgGb8rsgpWOvDWHWLSId5jufWvkITnylOoPftgTyxA22tL0hfVgjeH
pNaY4w+YFWZsj7AS1Eil6gnoD+i7DrZKT9AKkga7wMoe3IaShZm0rM0SPaw4
LZ0k8OiBz/akMW7rpK2zOstfnKPDnJEYE6cDqdaxhhxOPUn+65fy1JNicN7T
12c9dYGr0g7OO1Ps0NWrWRZfSFb4wloPqgk6K3ML8vfvVd44X3tOlGJRdPs4
ZT9Ep6Gu`

func TestDecode(t *testing.T) {
	decoded, err := decodeEmbeddedData(encoded)
	assert.Nil(t, err)
	assert.Equal(t, decoded, decodedExpectation)
}
